//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Disco
    {
        public int IdDisco { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.TimeSpan> Duracion { get; set; }
        public System.DateTime Anio { get; set; }
        public Nullable<int> Ventas { get; set; }
        public string Disponibilidad { get; set; }
        public int IdArtista { get; set; }
        public int IdGenero { get; set; }
        public int IdDistribuidora { get; set; }
    
        public virtual Artista Artista { get; set; }
        public virtual Distribuidora Distribuidora { get; set; }
        public virtual GeneroMusical GeneroMusical { get; set; }
    }
}
